# Generated by Django 5.2.10 on 2026-03-01 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Question set name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uses_employees', models.BooleanField(default=True)),
                ('uses_projects', models.BooleanField(default=False)),
                ('predict_query', models.TextField(help_text='SQL query for predict section')),
                ('predict_option1', models.CharField(max_length=500)),
                ('predict_option2', models.CharField(max_length=500)),
                ('predict_option3', models.CharField(max_length=500)),
                ('predict_option4', models.CharField(max_length=500)),
                ('predict_correct_answer', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('investigate_q1', models.TextField(help_text='Investigation question 1')),
                ('investigate_a1', models.TextField(help_text='Correct answer 1')),
                ('investigate_q2', models.TextField(help_text='Investigation question 2')),
                ('investigate_a2', models.TextField(help_text='Correct answer 2')),
                ('investigate_q3', models.TextField(help_text='Investigation question 3')),
                ('investigate_a3', models.TextField(help_text='Correct answer 3')),
                ('modify_task', models.TextField(help_text='What should students modify?')),
                ('modify_initial_query', models.TextField(help_text='Semi-correct query to modify')),
                ('modify_correct_query', models.TextField(help_text='Correct query after modification')),
                ('make_task', models.TextField(help_text='Task for make section')),
                ('make_correct_query', models.TextField(help_text='Correct SQL query for make section')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_question_sets',
                'ordering': ['-created_at'],
            },
        ),
    ]
